const PAGES: SEoPagesProps = {
  homepage: {
    title: 'Homepage',
    description:
      'Welcome to the world of connectivity, where conversations, ideas, and experiences converge. Our Social Media Add homepage is your gateway to a digital universe, designed to empower, engage, and entertain. Here, you can create and share content, connect with friends, family, and influencers across the globe, and stay updated with the latest trends and news. Our user-friendly interface ensures seamless navigation, while robust privacy settings safeguard your online presence. Dive into the dynamic realm of social media and redefine your digital experience.',
    keywords: [
      'Connectivity',
      'Content Creation',
      'Global Interaction',
      'Latest Trends',
      'News Updates',
      'User-friendly Interface',
      'Privacy Settings',
      'Social Media',
      'Digital Experience',
      'Seamless Navigation',
    ],
  },
  '404': {
    title: '404 Page Not Found',
    description:
      'The 404 page of our social media app is designed to be engaging and user-friendly. It features a playful, minimalistic design with a friendly error message, indicating that the requested page cannot be found. The page includes a search bar to help users easily navigate back to their desired content. It also showcases a rotating selection of popular posts and trending topics to re-engage users. The 404 page is not just an error page, but a unique opportunity to retain users and guide them back to active engagement.',
    keywords: [
      '404 Page',
      'Social Media App',
      'User-friendly',
      'Engaging',
      'Minimalistic Design',
      'Error Message',
      'Search Bar',
      'Navigation',
      'Popular Posts',
      'Trending Topics',
    ],
  },
  bookmarks: {
    title: 'Bookmarks',
    description: `The Bookmarks page on a social media app is a personalized space where users can save and organize content they find interesting or wish to revisit later. This feature allows users to easily access their favorite posts, articles, videos, or images without having to search through their feed. Users can categorize their saved content into different folders or tags for efficient retrieval. The Bookmarks page is a testament to the app's commitment to user convenience, enabling a more tailored and engaging social media experience.`,
    keywords: [
      'Bookmarks',
      'Social media app',
      'Personalized',
      'Saved content',
      'Organize',
      'Favorite posts',
      'Articles',
      'Videos',
      'Images',
      'User convenience',
    ],
  },
  chat: {
    title: 'Chat',
    description: `Chat Page is a dynamic social media app that revolutionizes the way people connect and communicate. With its sleek and user-friendly interface, Chat Page offers a seamless experience for users to engage in real-time conversations with friends, family, and even new acquaintances. The app boasts a wide range of features, including private messaging, group chats, and voice and video calls, ensuring that users can stay connected no matter where they are. Additionally, Chat Page allows users to share photos, videos, and other media, making conversations more interactive and engaging. With advanced privacy settings and robust security measures, users can feel confident that their personal information is protected. Whether it's catching up with old friends or meeting new ones, Chat Page is the go-to app for fostering meaningful connections in the digital age.`,
    keywords: [
      'Social media app',
      'Chat',
      'Real-time conversations',
      'Private messaging',
      'Group chats',
      'Voice and video calls',
      'Photos',
      'Videos',
      'Privacy settings',
      'Meaningful connections',
    ],
  },
  contactUs: {
    title: 'Contact Us',
    description: `Our Contact Us page is designed to provide users with a seamless and efficient way to reach out to us for any queries, concerns, or feedback regarding our social media app. With a user-friendly interface, users can easily locate the Contact Us section and find the necessary information to get in touch with our dedicated support team. We offer multiple contact options, including a direct email address, a phone number, and a contact form, ensuring that users can choose the method that suits them best. Our team is committed to providing prompt and personalized assistance, addressing user inquiries with professionalism and care. Whether it's technical support, account-related issues, or suggestions for app improvements, we encourage users to reach out to us through our Contact Us page, as their feedback is invaluable in helping us enhance their social media experience.`,
    keywords: [
      'Contact Us',
      'Feedback',
      'Queries',
      'Concerns',
      'Support',
      'Help',
      'Inquiries',
      'Issues',
      'Enhancement',
      'Professionalism',
    ],
  },
  forgetPassword: {
    title: 'Forget Password',
    description: `One of the key features of our app is the "Forgot Password" page. This page allows you to easily reset your password if you have forgotten it. You can simply enter your email address or username and we will send you a link to reset your password. This process is very simple and easy to follow, making it easy for you to access all the features of our app.`,
    keywords: [
      'Social media app',
      'Forget password page',
      'User-friendly interface',
      'Easy navigation',
      'Clear instructions',
      'Contact us page',
      'Customer support',
      'Convenience',
      'Enjoyment',
      'Features',
    ],
  },
  groups: {
    title: 'Groups',
    description: `Whether you're looking for a group to share your passion for cooking or a group to learn a new language, our Groups page is the perfect place to connect with others who share your interests. With a wide range of topics to choose from, you'll find a group that's just right for you.`,
    keywords: [
      'Social media',
      'Groups',
      'Community',
      'Connectivity',
      'Collaboration',
      'Networking',
      'Participation',
      'Engagement',
      'Participatory',
      'Interactive',
    ],
  },
  joinUs: {
    title: 'Join Us',
    description: `Our social media app is designed to be user-friendly and intuitive, with a clean and modern interface that makes it easy to navigate. Whether you're looking for a quick chat with a friend or a more comprehensive discussion on a particular topic, our app makes it easy to connect with others and share your thoughts with the world.`,
    keywords: [
      'Social media app',
      'Registration/login page',
      'Connect with friends and family',
      'Share thoughts and ideas',
      'Stay up-to-date with news and trends',
      'User-friendly interface',
      'Clean and modern design',
      'Easy-to-use features',
      'Multimedia content sharing',
      'Real-time messaging and notifications',
    ],
  },
  notification: {
    title: 'Notification',
    description: `Our notification page is designed to be user-friendly and easy to navigate. You can customize your notification settings to receive alerts only when there is new content, or receive alerts for every new post. You can also choose which platforms you want to receive notifications from, so you only receive alerts from the platforms that matter to you.`,
    keywords: [
      'Social media',
      'Notifications',
      'Updates',
      'Trends',
      'News',
      'Industry',
      'User-friendly',
      'Easy to navigate',
      'Customizable',
      'Platform-specific',
    ],
  },
  profile: {
    title: 'Profile',
    description: `Our profile page is where you can customize your profile and share it with the world. You can add a profile picture, change your bio, and choose which categories you're interested in. This will help you get to know your followers and build relationships with them.`,
    keywords: [
      'Social Media App',
      'Profile Page',
      'Connect with People',
      'Inspiration',
      'Share Thoughts',
      'Stay Connected',
      'Customize Profile',
      'Followers',
      'Relationships',
      'Posts',
    ],
  },
  setting: {
    title: 'Setting',
    description: `Welcome to the Social Media App Setting page! Here, you can customize your app's settings to suit your needs. From here, you can change the app's name, icon, and color scheme. You can also choose which social media platforms you want to integrate with your app, such as Facebook, Twitter, and Instagram. Additionally, you can set up notifications to be sent to you when new posts are made on your chosen platforms. With these settings in place, your Social Media App will be ready to go and help you stay connected with your friends and family on any device. So, what are you waiting for? Start customizing your Social Media App today!`,
    keywords: [
      'Social Media App',
      'Settings',
      'Customization',
      'Integration',
      'Notifications',
      'Platforms',
      'Devices',
      'Connections',
      'Stay connected',
      'Helpful app',
    ],
  },
  editorHelp: {
    title: 'Editor',
    description: `This page is designed to provide you with all the information you need to edit your social media app. Whether you're a professional graphic designer or just starting out, this page is a must-read for anyone looking to improve their app's design and functionality. Editing your social media app is an important process that requires a lot of time and effort. By following these tips and best practices, you can create an app that is both visually appealing and easy to use.`,
    keywords: [
      'design',
      'social media app',
      'editing',
      'interface',
      'user experience',
      'tips',
      'best practices',
      'vector-based design',
      'responsive design',
      'consistent layout',
      'consistent color scheme',
      'clear and concise language.',
    ],
  },
  calenderHelp: {
    title: 'Calender',
    description: `Calender is a social media app that allows users to create and share events with their friends and family. With Calender, you can create events on your own calendar, invite friends and family to attend, and share the event details with others. You can also set reminders and notifications to keep you informed about the event.`,
    keywords: [
      'social media app',
      'event planning',
      'event creation',
      'event invitations',
      'event sharing',
      'event notifications',
      'event reminders',
      'event templates',
      'event management',
      'event organization.',
    ],
  },
  help: {
    title: 'Help',
    description: `Welcome to our social media app Help page! Here you will find answers to common questions and issues you may encounter while using our app. To create a new account, tap on the "Sign Up" button in the bottom right corner of the screen. Enter your email address and create a strong password. Confirm your password by typing it again. Tap on the "Sign Up" button to create your account. To log in to your account, open the app on your device. Tap on the "Log In" button in the bottom right corner of the screen. Enter your email address and password. Tap on the "Log In" button to log in to your account. If you have forgotten your password, tap on the "Forgot Password" button to reset it. If you continue to have issues, contact our support team for assistance.`,
    keywords: [
      'Social media app',
      'Help page',
      'Frequently asked questions',
      'Common issues',
      'Account creation',
      'Log in',
      'Password reset',
      'Support team',
      'Contact us',
      'Common questions and issues',
    ],
  },
  postDetails: {
    title: 'Post Details',
    description: `Welcome to the Post Details page of our social media app! Here, you can view the details of a specific post, including its content, author, likes, and comments. To get started, simply tap on the post you want to view. You'll be taken to a page that displays the post's content, along with the author's profile picture and name. From there, you can tap on the author's name to view their profile, where you can see their bio, posts, and followers. To like or comment on the post, simply tap the corresponding icons in the bottom toolbar. Have fun exploring our app!`,
    keywords: [
      'app',
      'social media',
      'post',
      'details',
      'content',
      'author',
      'likes',
      'comments',
      'profile',
      'bio',
      'posts',
      'followers',
      'explore',
      'fun.',
    ],
  },
  results: {
    title: 'Results',
    description: `Welcome to our social media app results page! Our app helps you find the perfect match for your interests and lifestyle. With our advanced search filters, you can quickly find the perfect partner for any occasion. Whether you're looking for a date night partner, a romantic interest, or just someone to share your passions with, we've got you covered. Our app uses advanced algorithms to match you with the perfect person, just like our own social media app. So sit back, relax, and let us help you find the love of your life. Sign up today and start finding your perfect match today!`,
    keywords: [
      'Social media app',
      'Matchmaking',
      'Love',
      'Date night',
      'Romance',
      'Passion',
      'Lifestyle',
      'Partner',
      'Finding partner',
      'Advanced search filters',
    ],
  },
  events: {
    title: 'Events',
    description: `Welcome to the Events page of our social media app! Here, you can find all the latest and upcoming events happening around you. Whether it's a concert, a meetup, or a social event, we've got you covered. With Events, you can easily keep track of what's happening in your area and plan your next event. From music festivals to sports events, we've got everything you need to keep up with the latest happenings. So, what are you waiting for? Sign up for an account today and start exploring the world of Events!`,
    keywords: [
      'social media',
      'events',
      'concerts',
      'meetups',
      'music festivals',
      'sports events',
      'art events',
      'food events',
      'film events',
      'community events',
    ],
  },
};

export { PAGES };
